task_name: banana_plate_room_simple

camera:
  grasp_cam:
    res: [1280, 720]
    pos: [0, 0, 1.5]
    lookat: [0, 0, 0.0]
    fov: 30
    GUI: False
  desk_cam:
    res: [1280, 720]
    pos: [1.5, 0.0, 1]
    lookat: [0, 0, 0.25]
    fov: 60
    GUI: False

background:
  asset: assets/room_simple/object.urdf
  mesh_asset: assets/room_simple/room.obj
  simple_mesh_asset: assets/room_simple/simple_room.obj

object_active:
  asset: outputs/banana-20250813_150647_221/object.urdf
  mesh_asset: outputs/banana-20250813_150647_221/mesh_w_vertex_color_abs.ply
  pos_range:
    x: [-30.0, 20.0] # cm
    y: [-40.0, 40.0] # cm
  default_position:
    x: -15.0 # cm
    y: -15.0 # cm
  up_axis: z
  height_thres: 0.4 # cm
  motion_1_height: 20 # cm
  skill_1_height: 7.2 # cm
  motion_2_height: 20 # cm
  skill_2_height: 12 # cm
  physic_params:
    mass: 1.0
    friction: 0.2
    com_shift: [0, 0, 0]
    friction_ratio: 4.54689731331836
    mass_shift: -0.2414437050891564
    com_shift: [0.017808304444272453, 0.030200377174884798, -0.009719295200933715]
    
object_passive:
  asset: outputs/pink-20250627_184711_116/object.urdf
  mesh_asset: outputs/pink-20250627_184711_116/mesh_w_vertex_color_abs.ply
  pos_range:
    x: [-0.001, 0.0] # cm
    y: [-0.001, 0.0] # cm
  default_position:
    x: 0.0 # cm
    y: 0.0 # cm
  up_axis: z

far_threshold: 0.35
near_threshold: 0.08
collision_detection: True