task_name: banana_plate
background:
  asset: outputs/background-20250814_232642_441/splitted_point_cloud/object.urdf
robot:
  asset: assets/robot/franka_description/franka_panda_mobile_xy_tz.urdf
  robot_to_table_height: 1.58 # cm
  close_thres: 1.0 #cm
object_active:
  asset: outputs/banana-20250813_150647_221/object.urdf
  mesh_asset: outputs/banana-20250813_150647_221/mesh_w_vertex_color_abs.ply
  pos_range:
    x: [42.0, 82.0] # cm
    y: [-25.0, 15.0] # cm
  default_position:
    x: 62.0 # cm
    y: -15.0 # cm
  up_axis: z
  height_thres: 0.4 # cm
  motion_1_height: 20 # cm
  skill_1_height: 6.2 # cm
  motion_2_height: 20 # cm
  skill_2_height: 12 # cm
object_passive:
  asset: outputs/pink-20250627_184711_116/object.urdf
  mesh_asset: outputs/pink-20250627_184711_116/mesh_w_vertex_color_abs.ply
  pos_range:
    x: [42.0, 82.0] # cm
    y: [-25.0, 15.0] # cm
  default_position:
    x: 62.0 # cm
    y: 5.0 # cm
  up_axis: z

far_threshold: 0.15
near_threshold: 0.08
collision_detection: True