task_name: close_door
background:
  asset: outputs/background-20250814_232642_441/splitted_point_cloud/object.urdf
robot:
  asset: xml/franka_emika_panda/panda.xml
  robot_to_table_height: 1.58 # cm
  close_thres: 0.0 #cm
object_active:
  asset: outputs/computer-20250628_105001_551/object_abs.urdf
  mesh_asset: outputs/computer-20250628_105001_551/mesh_w_vertex_color_abs.ply
  pos_range:
    x: [42.0, 82.0] # cm
    y: [-25.0, 15.0] # cm
  rotation_range: [-15, 15] # degree
  joint_angle_range: [-12.5, -7.5] # degree
  default_position:
    x: 62.0 # cm
    y: -15.0 # cm
  default_rotation: 90 # degree
  default_joint_angle: -10 # degree
  up_axis: z
  height_thres: 0.4 # cm

far_threshold: 0.15
near_threshold: 0.08
collision_detection: True