task_name: cup_plate
background:
  asset: outputs/background-20250814_232642_441/splitted_point_cloud/object.urdf
robot:
  asset: xml/franka_emika_panda/panda.xml
  robot_to_table_height: 1.58 # cm
  close_thres: 0.25 #cm
object_active:
  asset: outputs/cup-20250814_171218_703/object.urdf
  mesh_asset: outputs/cup-20250814_171218_703/mesh_w_vertex_color_abs.ply
  pos_range:
    x: [42.0, 82.0] # cm
    y: [-25.0, 15.0] # cm
  default_position:
    x: 62.0 # cm
    y: -15.0 # cm
  up_axis: y
  height_thres: 0.4 # cm
  motion_1_height: 20 # cm
  skill_1_height: 5.6 # cm
  motion_2_height: 30 # cm
  skill_2_height: 16 # cm
object_passive:
  asset: outputs/pink-20250627_184711_116/object.urdf
  mesh_asset: outputs/pink-20250627_184711_116/mesh_w_vertex_color_abs.ply
  pos_range:
    x: [42.0, 82.0] # cm
    y: [-25.0, 15.0] # cm
  default_position:
    x: 62.0 # cm
    y: 5.0 # cm
  up_axis: z

far_threshold: 0.15
near_threshold: 0.08
collision_detection: False